"""empty message

Revision ID: 16e19af60f65
Revises: 3682f4f828de
Create Date: 2024-03-02 01:59:34.769795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e19af60f65'
down_revision: Union[str, None] = '3682f4f828de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_user', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_user', 'date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
