"""empty message

Revision ID: 5ca891f48470
Revises: 3f77b2aacf1e
Create Date: 2024-03-02 01:34:12.579440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca891f48470'
down_revision: Union[str, None] = '3f77b2aacf1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('date', sa.Enum('fifth', 'sixth', name='date'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'date')
    # ### end Alembic commands ###
