"""empty message

Revision ID: 86f53c214a58
Revises: 16e19af60f65
Create Date: 2024-03-02 02:13:35.684208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '86f53c214a58'
down_revision: Union[str, None] = '16e19af60f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('hotel_info', sa.Boolean(), nullable=False, server_default=sa.TextClause("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'hotel_info')
    # ### end Alembic commands ###
